{
 "title": "DSM",
 "description": "DSM Servers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Uptime Zabbix-Verwaltung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"10.103.7.7:9100\",job=\"prometheus\"} - node_boot_time_seconds{instance=\"10.103.7.7:9100\",job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Zabbix-Verwaltung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"10.103.7.7:9100\",job=\"prometheus\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"10.103.7.7:9100\",job=\"prometheus\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Zabbix-Verwaltung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_MemTotal_bytes{instance=\"10.103.7.7:9100\",job=\"prometheus\"}[$__rate_interval]) - avg_over_time(node_memory_MemFree_bytes{instance=\"10.103.7.7:9100\",job=\"prometheus\"}[$__rate_interval])) / (avg_over_time(node_memory_MemTotal_bytes{instance=\"10.103.7.7:9100\",job=\"prometheus\"}[$__rate_interval]) )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5m avg Zabbix-Verwaltung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{instance=\"10.103.7.7:9100\",job=\"prometheus\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"10.103.7.7:9100\",job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "15m avg Zabbix-Verwaltung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{instance=\"10.103.7.7:9100\",job=\"prometheus\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"10.103.7.7:9100\",job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Zabbix-Verwaltung",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"10.103.7.7:9100\",job=\"prometheus\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"10.103.7.7:9100\",job=\"prometheus\",device!~'rootfs'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current OpenVPN Clients",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum(label_replace(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}, \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address))"
    },
    {
     "expr": "sum(label_replace(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}, \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address)"
    }
   ]
  },
  {
   "title": "Uptime Zabbix Schule",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"172.17.16.5:9100\",job=\"prometheus\"} - node_boot_time_seconds{instance=\"172.17.16.5:9100\",job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Zabbix-Schule",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"172.17.16.5:9100\",job=\"prometheus\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"172.17.16.5:9100\",job=\"prometheus\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Zabbix-Schule",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_MemTotal_bytes{instance=\"172.17.16.5:9100\",job=\"prometheus\"}[$__rate_interval]) - avg_over_time(node_memory_MemFree_bytes{instance=\"172.17.16.5:9100\",job=\"prometheus\"}[$__rate_interval])) / (avg_over_time(node_memory_MemTotal_bytes{instance=\"172.17.16.5:9100\",job=\"prometheus\"}[$__rate_interval]) )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5m avg Zabbix-Schule",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{instance=\"172.17.16.5:9100\",job=\"prometheus\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"172.17.16.5:9100\",job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "15m avg Zabbix-Schule",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{instance=\"172.17.16.5:9100\",job=\"prometheus\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"172.17.16.5:9100\",job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Zabbix-Schule",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"172.17.16.5:9100\",job=\"prometheus\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"172.17.16.5:9100\",job=\"prometheus\",device!~'rootfs'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime Hesk",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"10.103.7.8:9100\",job=\"prometheus\"} - node_boot_time_seconds{instance=\"10.103.7.8:9100\",job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Hesk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"10.103.7.8:9100\",job=\"prometheus\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"10.103.7.8:9100\",job=\"prometheus\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Hesk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_MemTotal_bytes{instance=\"10.103.7.8:9100\",job=\"prometheus\"}[$__rate_interval]) - avg_over_time(node_memory_MemFree_bytes{instance=\"10.103.7.8:9100\",job=\"prometheus\"}[$__rate_interval])) / (avg_over_time(node_memory_MemTotal_bytes{instance=\"10.103.7.8:9100\",job=\"prometheus\"}[$__rate_interval]) )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5m avg Hesk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{instance=\"10.103.7.8:9100\",job=\"prometheus\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"10.103.7.8:9100\",job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "15m avg Hesk",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{instance=\"10.103.7.8:9100\",job=\"prometheus\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"10.103.7.8:9100\",job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Hesk",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"10.103.7.8:9100\",job=\"prometheus\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"10.103.7.8:9100\",job=\"prometheus\",device!~'rootfs'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPN Logins",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(count_values(\"connection_time\", count_over_time(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))by(common_name)>1)",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "VPN Received",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_received_bytes_total[1d]))"
    }
   ]
  },
  {
   "title": "VPN Sent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_sent_bytes_total[1d]))"
    }
   ]
  },
  {
   "title": "Uptime Snipe-IT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"10.103.7.9:9100\",job=\"prometheus\"} - node_boot_time_seconds{instance=\"10.103.7.9:9100\",job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Snipe-IT",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"10.103.7.9:9100\",job=\"prometheus\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"10.103.7.9:9100\",job=\"prometheus\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Snipe-IT",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_MemTotal_bytes{instance=\"10.103.7.9:9100\",job=\"prometheus\"}[$__rate_interval]) - avg_over_time(node_memory_MemFree_bytes{instance=\"10.103.7.9:9100\",job=\"prometheus\"}[$__rate_interval])) / (avg_over_time(node_memory_MemTotal_bytes{instance=\"10.103.7.9:9100\",job=\"prometheus\"}[$__rate_interval]) )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5m avg Snipe-IT",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{instance=\"10.103.7.9:9100\",job=\"prometheus\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"10.103.7.9:9100\",job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "15m avg Snipe-IT",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{instance=\"10.103.7.9:9100\",job=\"prometheus\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"10.103.7.9:9100\",job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Snipe-IT",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"10.103.7.9:9100\",job=\"prometheus\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"10.103.7.9:9100\",job=\"prometheus\",device!~'rootfs'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPN Traffic",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Log Update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-openvpn_status_update_time_seconds{job=\"openvpn-metrics\"}"
    }
   ]
  },
  {
   "title": "Uptime Prometheus",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"10.103.7.10:9100\",job=\"prometheus\"} - node_boot_time_seconds{instance=\"10.103.7.10:9100\",job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Prometheus",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"10.103.7.10:9100\",job=\"prometheus\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"10.103.7.10:9100\",job=\"prometheus\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Prometheus",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((avg_over_time(node_memory_MemTotal_bytes{instance=\"10.103.7.10:9100\",job=\"prometheus\"}[$__rate_interval]) - avg_over_time(node_memory_MemFree_bytes{instance=\"10.103.7.10:9100\",job=\"prometheus\"}[$__rate_interval])) / (avg_over_time(node_memory_MemTotal_bytes{instance=\"10.103.7.10:9100\",job=\"prometheus\"}[$__rate_interval]) )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5m avg Prometheus",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{instance=\"10.103.7.10:9100\",job=\"prometheus\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"10.103.7.10:9100\",job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "15m avg Prometheus",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{instance=\"10.103.7.10:9100\",job=\"prometheus\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"10.103.7.10:9100\",job=\"prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"10.103.7.10:9100\",job=\"prometheus\",device!~'rootfs'} - node_filesystem_avail_bytes{instance=\"10.103.7.10:9100\",job=\"prometheus\",device!~'rootfs'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top VPN Network Activity",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum(rate(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[2m]))by(common_name))",
     "legendFormat": "{{ common_name }} - Rx"
    },
    {
     "expr": "topk(6, sum(rate(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[2m]))by(common_name))",
     "legendFormat": "{{ common_name }} - Tx"
    },
    {
     "expr": "sum(bottomk(scalar(openvpn_openvpn_server_connected_clients)-6, sum(rate(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[2m]))by(common_name)))",
     "legendFormat": "Rx - Others"
    },
    {
     "expr": "sum(bottomk(scalar(openvpn_openvpn_server_connected_clients)-6, sum(rate(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1m]))by(common_name)))",
     "legendFormat": "Tx - Others"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_up{job=\"openvpn-metrics\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_openvpn_server_connected_clients"
    }
   ]
  }
 ]
}