---
- name: Just get information about the repository whether or not it has already been cloned locally
  git:
    repo: 'https://github.com/CrunchyData/postgresql-prometheus-adapter.git'
    dest: /tmp/postgresql-prometheus-adapter/

- name: Install make
  apt:
    name: make
    state: present

- name: Install golang
  package:
    name: golang
    state: present

- name: 1 go
  shell:
    cmd: go mod download github.com/go-kit/kit
    chdir: /tmp/postgresql-prometheus-adapter/

- name: 2 go
  command:
    cmd: go get github.com/crunchydata/postgresql-prometheus-adapter
    chdir: /tmp/postgresql-prometheus-adapter/

- name: Make
  command:
    cmd: make
    chdir: /tmp/postgresql-prometheus-adapter/

- name: Copy cluster ID
  copy:
    src:  "~/Desktop/very_secure_dir/postgresql_id.txt"
    dest: /tmp/postgresql_id.txt

- name: Read cluster ID
  shell: |
    cat /tmp/postgresql_id.txt
  register: file_content

- name: Start adapter
  shell: "/tmp/postgresql-prometheus-adapter/postgresql-prometheus-adapter"
  environment:
    DATABASE_URL: postgres://alice:1234qwe1234@c-{{ file_content.stdout }}.rw.mdb.yandexcloud.net:6432/my_db
  async: 2592000 #month
  poll: 0
