---
# defaults file for roles/grafana

grafana_admin_user: "admin"
grafana_admin_password: "password"
grafana_dir_dashboards: /tmp/dashboards
grafana_dir_pro: /tmp/provisioning
grafana_dir_pro2: /tmp/provisioning2
grafana_data_dir: "/var/lib/grafana"
grafana_dashboards_dir: "dashboards"
grafana_service_name: "grafana"